sched: Introduce BORE Scheduler (4.2.4)
BORE (Burst-Oriented Response Enhancer) is enhanced versions of CFS (Completely Fair Scheduler)
and EEVDF (Earliest Eligible Virtual Deadline First) Linux schedulers. Developed with the aim of
maintaining these schedulers' high performance while delivering resilient responsiveness to user
input under as versatile load scenario as possible.

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/stable/linux-4.19-bore

0001-linux4.19.y-bore4.2.4.patch
0002-constgran-vanilla-max.patch

[backslashxx]
adapt to msm-4.19, fixes

../kernel/sysctl.c:192:27: error: redefinition of 'three'
  192 | static int __maybe_unused three          = 3;
      |                           ^

../kernel/sched/fair.c:5662:6: error: use of undeclared identifier 'task_sleep'
 5662 |         if (task_sleep) {
      |             ^
--